# .github/workflows/test.yml

name: Test and Build

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run FibBot
        run: |
          ./scripts/fibbot
        env:
          ENABLE_FIB: true
          MAX_THRESHOLD: 1000

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          cargo build --release