name: Test FibBot
on:
  pull_request:
    types: [opened, edited]
permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run FibBot
        uses: ./action.yml
        with:
          enable_fib: true
          max_threshold: 1000
