name: Comment on Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: cargo build --release

      - name: Run FibBot
        run: |
          cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          ENABLE_FIB: true
          MAX_THRESHOLD: 1000
